export const home = {
  1: {
    name: "Домик в лесу",
    src: "img/home_anime.png",
    x: 250,
    y: 530,
    scale: 350,
  },
  2: {
    name: "Дом из земли",
    src: "img/home_mine.png",
    x: 80,
    y: 120,
    scale: 160,
  },
  3: {
    name: "Средний трейлер",
    src: "img/home_big_trailer.png",
    x: 700,
    y: 230,
    scale: 500,
  },
  4: {
    name: "Дом на районе",
    src: "img/home_cj.png",
    x: 500,
    y: 270,
    scale: 400,
  },
  5: {
    name: "Особняк тарелка",
    src: "img/home_plate.png",
    x: 360,
    y: 270,
    scale: 300,
  },
  6: {
    name: "Особняк с бассейном",
    src: "img/home_pool.png",
    x: 200,
    y: 270,
    scale: 300,
  },
  7: {
    name: "Хижина чудес",
    src: "img/home_mystery.png",
    x: 50,
    y: 470,
    scale: 250,
  },
};
